#!/bin/sh

. /lib/functions.sh
. /usr/share/gecoosac/runtime.sh

config_load gecoosac
config_get db_dir config db_dir '/etc/gecoosac/'

db_dir="$(normalize_directory "$db_dir")"
validate_directory "$db_dir" || exit 1

tail -n 100 "$db_dir/logs/gecoosac.log" 2>/dev/null
