#!/bin/sh

. /lib/functions.sh
. /usr/share/gecoosac/runtime.sh

config_load gecoosac
config_get db_dir config db_dir '/etc/gecoosac/'

db_dir="$(normalize_directory "$db_dir")"
validate_db_directory "$db_dir" || exit 1

log_file="$db_dir/logs/gecoosac.log"
[ -f "$log_file" ] || exit 0
: > "$log_file"
