#!/bin/sh

data_dir="$(uci -q get axonhub.main.data_dir)"
port="$(uci -q get axonhub.main.port)"
config_version="$(uci -q get axonhub.main.config_version)"
log_to_syslog="$(uci -q get axonhub.main.log_to_syslog)"
log_cleanup_days="$(uci -q get axonhub.main.log_cleanup_days)"
log_cleanup_schedule="$(uci -q get axonhub.main.log_cleanup_schedule)"
changed=0

if [ -z "$data_dir" ] || [ "$data_dir" = 'auto' ]; then
	data_dir="$(/usr/libexec/axonhub-find-storage)"
	uci -q set axonhub.main.data_dir="$data_dir"
	changed=1
fi

if [ -z "$port" ] || [ "$port" = 'auto' ] || { [ -z "$config_version" ] && [ "$port" = '8090' ]; }; then
	port="$(/usr/libexec/axonhub-random-port)"
	uci -q set axonhub.main.port="$port"
	changed=1
fi

if [ -z "$config_version" ]; then
	if [ -z "$log_to_syslog" ] || [ "$log_to_syslog" = '1' ]; then
		uci -q set axonhub.main.log_to_syslog='0'
		changed=1
	fi
fi

if [ -z "$log_cleanup_schedule" ]; then
	case "$log_cleanup_days" in
		0) log_cleanup_schedule='disabled' ;;
		''|*[!0-9]*) log_cleanup_schedule='weekly' ;;
		*)
			if [ "$log_cleanup_days" -le 3 ]; then
				log_cleanup_schedule='daily'
			elif [ "$log_cleanup_days" -le 21 ]; then
				log_cleanup_schedule='weekly'
			else
				log_cleanup_schedule='monthly'
			fi
			;;
	esac
	uci -q set axonhub.main.log_cleanup_schedule="$log_cleanup_schedule"
	changed=1
fi

case "$log_cleanup_schedule" in
	disabled|daily|weekly|monthly) ;;
	*)
		uci -q set axonhub.main.log_cleanup_schedule='weekly'
		changed=1
		;;
esac

if [ -n "$log_cleanup_days" ]; then
	uci -q delete axonhub.main.log_cleanup_days
	changed=1
fi

if [ "$config_version" != '3' ]; then
	uci -q set axonhub.main.config_version='3'
	changed=1
fi

[ "$changed" -eq 0 ] || uci -q commit axonhub

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@axonhub[-1]
	add ucitrack axonhub
	set ucitrack.@axonhub[-1].init=axonhub
	commit ucitrack
EOF

rm -rf /tmp/luci-*
exit 0
